collections:
  - name: datadog.dd
    version: 6.4.0
  - name: cloud.terraform
    version: 3.0.0
  - name: ansible.posix
    version: 1.6.2
  - name: nycmesh.common
    source: git+https://github.com/nycmeshnet/nycmesh-ansible.git
    type: git
    version: main
